default_context:
  project_name: '毕业实习'
  project_slug: '毕业实习'
  domain_main: 'beishangongzi.top'
  domain_staging: 'stag.beishangongzi.top'
  docker_swarm_stack_name_main: 'beishangongzi-top'
  docker_swarm_stack_name_staging: 'stag-beishangongzi-top'
  secret_key: '5e04067e73ccb3f1e8bcff1749d5d3de6b213980fb954dc7640c245198819a54'
  first_superuser: 'zhangruibin021@gmail.com'
  first_superuser_password: '123456'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.beishangongzi.top", "https://stag.beishangongzi.top", "https://beishangongzi.top", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '25'
  smtp_host: 'smtp.126.com'
  smtp_user: 'andyelizabeth021@126.com'
  smtp_password: 'OQONHJDDFBCEEBAS'
  smtp_emails_from_email: 'andyelizabeth021@126.com'
  postgres_password: '123456'
  pgadmin_default_user: 'zhangruibin021@gmail.com'
  pgadmin_default_user_password: '123456'
  traefik_constraint_tag: 'beishangongzi.top'
  traefik_constraint_tag_staging: 'stag.beishangongzi.top'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123456'
  sentry_dsn: ''
  docker_image_prefix: 'graduatioin-intern'
  docker_image_backend: 'graduatioin-internbackend'
  docker_image_celeryworker: 'graduatioin-internceleryworker'
  docker_image_frontend: 'graduatioin-internfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
